{{- range $scraper, $scraperValues := .Values.scrapers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$scraper}}-scraper-secret
type: Opaque
data:
  config.yml: {{ tpl ($.Files.Get "files/binance-scraper-config.yml") $ | b64enc }}
---
{{- end }}